version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: zakky
      POSTGRES_PASSWORD: 1164
      POSTGRES_DB: synapsis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: